#!/usr/bin/env bash
# RemitSave Africa - Bootstrap Script
# Installs dependencies, builds contracts, runs migrations, and starts all services.
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# Resolve repo root regardless of where the script is called from
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ─────────────────────────────────────────────────────────────────────────────
# 1. PREREQUISITE CHECKS
# ─────────────────────────────────────────────────────────────────────────────
check_cmd() {
    command -v "$1" &>/dev/null || error "'$1' not found. $2"
}

info "Checking prerequisites..."
check_cmd docker       "Install Docker: https://docs.docker.com/get-docker/"
check_cmd docker       "Ensure Docker daemon is running."
check_cmd cargo        "Install Rust: https://rustup.rs"
check_cmd node         "Install Node.js 20+: https://nodejs.org or 'nvm install 20'"
check_cmd npm          "Install Node.js 20+: https://nodejs.org"

# Soroban CLI (optional — only needed for contract deploy, not for local dev services)
if ! command -v soroban &>/dev/null; then
    warn "soroban CLI not found. Contract deploy/invoke will be skipped."
    warn "Install with: cargo install soroban-cli"
    SOROBAN_AVAILABLE=false
else
    SOROBAN_AVAILABLE=true
fi

# Rust wasm32 target
if ! rustup target list --installed | grep -q "wasm32-unknown-unknown"; then
    info "Adding wasm32-unknown-unknown Rust target..."
    rustup target add wasm32-unknown-unknown
fi

success "Prerequisites OK."

# ─────────────────────────────────────────────────────────────────────────────
# 2. ENVIRONMENT FILE
# ─────────────────────────────────────────────────────────────────────────────
if [ ! -f "$REPO_ROOT/.env" ]; then
    info "Creating .env from .env.example..."
    cat > "$REPO_ROOT/.env" <<'EOF'
# Auto-generated by bootstrap.sh — edit for your environment
STELLAR_RPC_URL=http://localhost:8000/soroban/rpc
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2025
DATABASE_URL=postgres://remitsave:remitsave_dev@localhost:5432/remitsave
REDIS_URL=redis://localhost:6379
NATS_URL=nats://localhost:4222
JWT_SECRET=local-dev-secret-change-in-prod
CONTRACT_REMIT_SAVE=
ANCHOR_COWRIE_API_KEY=
ANCHOR_VIBRANT_API_KEY=
CIRCLE_API_KEY=
SMTP_HOST=
SMS_PROVIDER_KEY=
EOF
    success ".env created."
else
    info ".env already exists — skipping."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. BUILD SOROBAN CONTRACTS
# ─────────────────────────────────────────────────────────────────────────────
info "Building Soroban contracts (wasm32 release)..."
(cd "$REPO_ROOT/contracts" && cargo build --target wasm32-unknown-unknown --release 2>&1) \
    && success "Contracts built." \
    || error "Contract build failed. Run 'cd contracts && cargo build --target wasm32-unknown-unknown --release' to debug."

# ─────────────────────────────────────────────────────────────────────────────
# 4. RUN CONTRACT TESTS
# ─────────────────────────────────────────────────────────────────────────────
info "Running contract tests..."
(cd "$REPO_ROOT/contracts" && cargo test 2>&1) \
    && success "Contract tests passed." \
    || error "Contract tests failed."

# ─────────────────────────────────────────────────────────────────────────────
# 5. BUILD BACKEND SERVICES
# ─────────────────────────────────────────────────────────────────────────────
info "Building backend services..."
(cd "$REPO_ROOT/backend" && cargo build 2>&1) \
    && success "Backend built." \
    || error "Backend build failed. Run 'cd backend && cargo build' to debug."

# ─────────────────────────────────────────────────────────────────────────────
# 6. INSTALL FRONTEND DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
info "Installing diaspora-app dependencies..."
(cd "$REPO_ROOT/frontend/diaspora-app" && npm install --prefer-offline 2>&1) \
    && success "Frontend dependencies installed." \
    || error "npm install failed."

# ─────────────────────────────────────────────────────────────────────────────
# 7. START INFRASTRUCTURE (Docker Compose)
# ─────────────────────────────────────────────────────────────────────────────
info "Starting Docker infrastructure (Postgres, Redis, Stellar)..."
docker compose -f "$REPO_ROOT/docker-compose.yml" up -d --wait 2>&1 \
    || { warn "'--wait' flag unsupported on older Docker Compose; retrying without it...";
         docker compose -f "$REPO_ROOT/docker-compose.yml" up -d; }

# Wait for Postgres to be healthy
info "Waiting for Postgres to be ready..."
for i in $(seq 1 30); do
    if docker exec remitsave-postgres pg_isready -U remitsave -d remitsave &>/dev/null; then
        success "Postgres is ready."
        break
    fi
    sleep 2
    [ "$i" -eq 30 ] && error "Postgres did not become ready in time."
done

# ─────────────────────────────────────────────────────────────────────────────
# 8. RUN DATABASE MIGRATIONS
# ─────────────────────────────────────────────────────────────────────────────
info "Running database migrations..."
for sql_file in "$REPO_ROOT/backend/migrations"/*.sql; do
    fname=$(basename "$sql_file")
    info "  Applying $fname..."
    docker exec -i remitsave-postgres \
        psql -U remitsave -d remitsave < "$sql_file" \
        && success "  $fname applied." \
        || warn "  $fname may have already been applied (ignoring error)."
done

# ─────────────────────────────────────────────────────────────────────────────
# 9. OPTIONAL: DEPLOY CONTRACT TO LOCAL STELLAR NETWORK
# ─────────────────────────────────────────────────────────────────────────────
if [ "${SOROBAN_AVAILABLE}" = "true" ] && [ "${DEPLOY_CONTRACTS:-false}" = "true" ]; then
    info "Deploying contracts to local Stellar network..."
    NETWORK=local bash "$REPO_ROOT/scripts/deploy.sh"
    success "Contracts deployed. See .env.deployment for addresses."
else
    info "Skipping contract deployment. To deploy, run:"
    info "  DEPLOY_CONTRACTS=true bash scripts/bootstrap.sh"
    info "  or: NETWORK=local bash scripts/deploy.sh"
fi

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        RemitSave Africa — Bootstrap Complete         ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Services running:"
echo "    • Postgres   → localhost:5432  (DB: remitsave)"
echo "    • Redis       → localhost:6379"
echo "    • Stellar RPC → localhost:8000/soroban/rpc"
echo ""
echo "  Next steps:"
echo "    • Start backend:  cd backend && cargo run -p auth-service"
echo "    • Start frontend: cd frontend/diaspora-app && npx expo start"
echo "    • Run all tests:  make test"
echo "    • Stop services:  docker compose down"
echo ""
